# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 458009733205980e11763f330f313532f645fd838280fb13984c6d774b68bc5d441698cc7081d34a3733a7fce7b63c743e9a3bafef4798672f0bb2936648c0f5

test:
  secret_key_base: d9f146e6ffc53ec50340ab5fc87704221e79e8d51db76e8889fd22401c3c8833a13c1cf1dfeba4d71083a7ea43067b1aaacef2c498618ec433e0a068afc83670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
